_schema: _schema
source: /
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    glob:
      -
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  featured_categories:
    path: _featured_categories
    name: Featured Categories
    icon: featured_video
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  featured_tags:
    path: _featured_tags
    name: Featured Tags
    icon: featured_video
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  projects:
    path: _projects
    name: Projects
    icon: eject
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  jekyll: true
timezone: Etc/GMT-9
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
